FROM mivia_turtlebot4

USER root
RUN apt update

RUN apt install xfce4 xfce4-goodies -y
RUN apt install xrdp -y
RUN update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper
RUN adduser xrdp ssl-cert 

USER mivia
WORKDIR /home/mivia/
ADD --chown=mivia run_xrdp.bash .
RUN chmod +x run_xrdp.bash
RUN echo "xfce4-session" | tee .xsession

# RDP
EXPOSE 3389 
USER root

ENTRYPOINT ["bash", "/home/mivia/run_xrdp.bash" ]